### ISSUE TITLE
我要玩，可以吗？

### ISSUE THREAD

**Issue by TYH71** [kiritowu/pong-ai#13]
> as the title states

**Comment by kiritowu** [comment]
@TYH71 atm since it is not fully released yet with documentations, now wat you can wish for is clone main branch and run the ps1 script

**Comment by TYH71** [comment]
@kiritowu is this gonna be deployed to online or an edge device?

**Comment by kiritowu** [comment]
> @kiritowu is this gonna be deployed to online or an edge device?

Future plan🥰

**Comment by TYH71** [comment]
oof
